fix: check parent permission
leam-tech/frappe pull request #5
Opened 2021-10-23 05:46 UTC by e-lobo

2021-10-23 06:50 UTC, fahimalizain requested changes

2021-10-23 06:50 UTC, fahimalizain commented on frappe/model/db_query.py
> +		if child_doctype and not len(list(filter(lambda table_field: table_field.parent == parent, table_fields))):
@e-lobo shouldn't we validate `options` too ?
```suggestion
		if child_doctype and not len(list(filter(lambda table_field: table_field.parent == parent and table_field.options == child_doctype, table_fields))):
```

2021-10-23 07:21 UTC, fahimalizain approved these changes
👍🏼 👍🏼

2021-10-23 14:57 UTC, Abadulrehman approved these changes

2021-10-24 08:52 UTC, assemmarwan approved these changes

2021-10-24 08:58 UTC, merged